name = "GasChromatographySystems"
uuid = "2a17fa6e-c440-4af9-acac-c1be9e3a006f"
authors = ["Jan Leppert <jleppert@uni-bonn.de>"]
version = "0.1.2"

[deps]
GasChromatographySimulator = "dd82b6e2-56ef-419d-b271-0be268cb65f5"
GasChromatographyTools = "b1a91d42-e520-41a6-b75d-584445aea833"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
GasChromatographySimulator = "0.1.7"
GasChromatographyTools = "0.1.5"
Reexport = "1.2.2"
julia = "1.5.3"
