name = "GasChromatographySystems"
uuid = "2a17fa6e-c440-4af9-acac-c1be9e3a006f"
authors = ["Jan Leppert <jleppert@uni-bonn.de>"]
version = "0.1.0"

[deps]
GasChromatographySimulator = "dd82b6e2-56ef-419d-b271-0be268cb65f5"

[compat]
GasChromatographySimulator = "0.1"
julia = "1.5.3"
